# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: openjdk11

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
    - $HOME/.m2

# https://docs.travis-ci.com/user/database-setup/#mysql
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS university;'